version: '3'

services:
    bot:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        container_name: discord-reddit-bot
        env_file:
            - .env
        environment:
            - TZ=America/Sao_Paulo
        volumes:
            - ./logs:/discord-bot/src/logs
